# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1304, 803)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 30, 931, 711))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.matlayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.matlayout.setContentsMargins(0, 0, 0, 0)
        self.matlayout.setObjectName("matlayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(990, 30, 291, 291))
        self.widget.setObjectName("widget")
        self.toolsVLayout = QtWidgets.QVBoxLayout(self.widget)
        self.toolsVLayout.setContentsMargins(0, 0, 0, 0)
        self.toolsVLayout.setObjectName("toolsVLayout")

        self.btnDraw = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDraw.sizePolicy().hasHeightForWidth())
        self.btnDraw.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnDraw.setFont(font)
        self.btnDraw.setObjectName("btnDraw")
        self.toolsVLayout.addWidget(self.btnDraw)

        self.btnClear = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDraw.sizePolicy().hasHeightForWidth())
        self.btnDraw.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnDraw")
        self.toolsVLayout.addWidget(self.btnClear)

        self.cntTradesRadioBtn = QtWidgets.QRadioButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cntTradesRadioBtn.sizePolicy().hasHeightForWidth())
        self.cntTradesRadioBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cntTradesRadioBtn.setFont(font)
        self.cntTradesRadioBtn.setObjectName("cntTradesRadioBtn")
        self.toolsVLayout.addWidget(self.cntTradesRadioBtn)
        self.profitRadioBtn = QtWidgets.QRadioButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profitRadioBtn.sizePolicy().hasHeightForWidth())
        self.profitRadioBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.profitRadioBtn.setFont(font)
        self.profitRadioBtn.setObjectName("cntTradesRadioBtn_2")
        self.toolsVLayout.addWidget(self.profitRadioBtn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1304, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnDraw.setText(_translate("MainWindow", "Нарисовать"))
        self.btnClear.setText(_translate("MainWindow", "Очистить"))
        self.cntTradesRadioBtn.setText(_translate("MainWindow", "Гистограмма сделок"))
        self.profitRadioBtn.setText(_translate("MainWindow", "График доходности"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
