from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1130, 792)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(280, 30, 821, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.accountsTab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(8)
        self.accountsTab.setFont(font)
        self.accountsTab.setObjectName("accountsTab")
        self.widget = QtWidgets.QWidget(self.accountsTab)
        self.widget.setGeometry(QtCore.QRect(30, 10, 631, 411))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.accountsLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.accountsLabel.setFont(font)
        self.accountsLabel.setObjectName("accountsLabel")
        self.verticalLayout_2.addWidget(self.accountsLabel)
        self.accountsTable = QtWidgets.QTableWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountsTable.sizePolicy().hasHeightForWidth())
        self.accountsTable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accountsTable.setFont(font)
        self.accountsTable.setObjectName("accountsTable")
        self.accountsTable.setColumnCount(2)
        self.accountsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.accountsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.accountsTable.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.accountsTable)
        self.accountsButtons = QtWidgets.QHBoxLayout()
        self.accountsButtons.setObjectName("accountsButtons")
        self.getAccountsBtn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.getAccountsBtn.setFont(font)
        self.getAccountsBtn.setObjectName("getAccountsBtn")
        self.accountsButtons.addWidget(self.getAccountsBtn)
        self.openAccountBtn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.openAccountBtn.setFont(font)
        self.openAccountBtn.setObjectName("openAccountBtn")
        self.accountsButtons.addWidget(self.openAccountBtn)
        self.closeAccountBtn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.closeAccountBtn.setFont(font)
        self.closeAccountBtn.setObjectName("closeAccountBtn")
        self.accountsButtons.addWidget(self.closeAccountBtn)
        self.verticalLayout_2.addLayout(self.accountsButtons)
        self.tabWidget.addTab(self.accountsTab, "")
        self.portfolioTab = QtWidgets.QWidget()
        self.portfolioTab.setObjectName("portfolioTab")
        self.layoutWidget_2 = QtWidgets.QWidget(self.portfolioTab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(40, 30, 631, 504))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.portfLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.portfLayout.setContentsMargins(0, 0, 0, 0)
        self.portfLayout.setObjectName("portfLayout")
        self.portfolioLabel = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portfolioLabel.sizePolicy().hasHeightForWidth())
        self.portfolioLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.portfolioLabel.setFont(font)
        self.portfolioLabel.setObjectName("portfolioLabel")
        self.portfLayout.addWidget(self.portfolioLabel)
        self.displayLayout = QtWidgets.QVBoxLayout()
        self.displayLayout.setObjectName("displayLayout")
        self.fullSubLt = QtWidgets.QHBoxLayout()
        self.fullSubLt.setObjectName("fullSubLt")
        self.fullSumLbl = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fullSumLbl.setFont(font)
        self.fullSumLbl.setObjectName("fullSumLbl")
        self.fullSubLt.addWidget(self.fullSumLbl)
        self.fullSumDisp = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.fullSumDisp.setObjectName("fullSumDisp")
        self.fullSubLt.addWidget(self.fullSumDisp)
        self.displayLayout.addLayout(self.fullSubLt)
        self.freeMoneyLayout = QtWidgets.QHBoxLayout()
        self.freeMoneyLayout.setObjectName("freeMoneyLayout")
        self.freeMoneyLbl = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.freeMoneyLbl.setFont(font)
        self.freeMoneyLbl.setObjectName("freeMoneyLbl")
        self.freeMoneyLayout.addWidget(self.freeMoneyLbl)
        self.freeMoneyDisp = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.freeMoneyDisp.setObjectName("freeMoneyDisp")
        self.freeMoneyLayout.addWidget(self.freeMoneyDisp)
        self.displayLayout.addLayout(self.freeMoneyLayout)
        self.sharesSumLt = QtWidgets.QHBoxLayout()
        self.sharesSumLt.setObjectName("sharesSumLt")
        self.sharesSumLbl = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sharesSumLbl.setFont(font)
        self.sharesSumLbl.setObjectName("sharesSumLbl")
        self.sharesSumLt.addWidget(self.sharesSumLbl)
        self.sharesSumDisp = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.sharesSumDisp.setObjectName("sharesSumDisp")
        self.sharesSumLt.addWidget(self.sharesSumDisp)
        self.displayLayout.addLayout(self.sharesSumLt)
        self.bondSumLt = QtWidgets.QHBoxLayout()
        self.bondSumLt.setObjectName("bondSumLt")
        self.bondsSumLbl = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bondsSumLbl.setFont(font)
        self.bondsSumLbl.setObjectName("bondsSumLbl")
        self.bondSumLt.addWidget(self.bondsSumLbl)
        self.bondsSumDisp = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.bondsSumDisp.setObjectName("bondsSumDisp")
        self.bondSumLt.addWidget(self.bondsSumDisp)
        self.displayLayout.addLayout(self.bondSumLt)
        self.etfSumLt = QtWidgets.QHBoxLayout()
        self.etfSumLt.setObjectName("etfSumLt")
        self.etfSumLbl = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.etfSumLbl.setFont(font)
        self.etfSumLbl.setObjectName("etfSumLbl")
        self.etfSumLt.addWidget(self.etfSumLbl)
        self.etfSumDisp = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.etfSumDisp.setObjectName("etfSumDisp")
        self.etfSumLt.addWidget(self.etfSumDisp)
        self.displayLayout.addLayout(self.etfSumLt)
        self.profitLt = QtWidgets.QHBoxLayout()
        self.profitLt.setObjectName("profitLt")
        self.profitLbl = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.profitLbl.setFont(font)
        self.profitLbl.setObjectName("profitLbl")
        self.profitLt.addWidget(self.profitLbl)
        self.profitDisp = QtWidgets.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.profitDisp.setFont(font)
        self.profitDisp.setObjectName("profitDisp")
        self.profitLt.addWidget(self.profitDisp)
        self.displayLayout.addLayout(self.profitLt)
        self.portfLayout.addLayout(self.displayLayout)
        self.controlMenu = QtWidgets.QHBoxLayout()
        self.controlMenu.setObjectName("controlMenu")
        self.getPortfolioBtn = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.getPortfolioBtn.setFont(font)
        self.getPortfolioBtn.setObjectName("getPortfolioBtn")
        self.controlMenu.addWidget(self.getPortfolioBtn)
        self.idAccountLbl = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.idAccountLbl.setFont(font)
        self.idAccountLbl.setObjectName("idAccountLbl")
        self.controlMenu.addWidget(self.idAccountLbl)
        self.idAccountInp = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idAccountInp.sizePolicy().hasHeightForWidth())
        self.idAccountInp.setSizePolicy(sizePolicy)
        self.idAccountInp.setMaximumSize(QtCore.QSize(16777215, 8777100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idAccountInp.setFont(font)
        self.idAccountInp.setObjectName("idAccountInp")
        self.controlMenu.addWidget(self.idAccountInp)
        self.portfLayout.addLayout(self.controlMenu)
        self.tabWidget.addTab(self.portfolioTab, "")
        self.toolsInfoTab = QtWidgets.QWidget()
        self.toolsInfoTab.setObjectName("toolsInfoTab")
        self.layoutWidget_5 = QtWidgets.QWidget(self.toolsInfoTab)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 10, 741, 541))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.toolsLayout = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.toolsLayout.setContentsMargins(0, 0, 0, 0)
        self.toolsLayout.setObjectName("toolsLayout")
        self.toolsLbl = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.toolsLbl.setFont(font)
        self.toolsLbl.setObjectName("toolsLbl")
        self.toolsLayout.addWidget(self.toolsLbl)
        self.toolsTable = QtWidgets.QTableWidget(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolsTable.sizePolicy().hasHeightForWidth())
        self.toolsTable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.toolsTable.setFont(font)
        self.toolsTable.setObjectName("toolsTable")
        self.toolsTable.setColumnCount(7)
        self.toolsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.toolsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.toolsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.toolsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.toolsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.toolsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.toolsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.toolsTable.setHorizontalHeaderItem(6, item)
        self.toolsLayout.addWidget(self.toolsTable)
        self.controlMenu_2 = QtWidgets.QHBoxLayout()
        self.controlMenu_2.setObjectName("controlMenu_2")
        self.getToolsBtn = QtWidgets.QPushButton(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.getToolsBtn.setFont(font)
        self.getToolsBtn.setObjectName("getToolsBtn")
        self.controlMenu_2.addWidget(self.getToolsBtn)
        self.filterMenu = QtWidgets.QGridLayout()
        self.filterMenu.setObjectName("filterMenu")
        self.sectorLbl = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sectorLbl.sizePolicy().hasHeightForWidth())
        self.sectorLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sectorLbl.setFont(font)
        self.sectorLbl.setObjectName("sectorLbl")
        self.filterMenu.addWidget(self.sectorLbl, 0, 0, 1, 1)
        self.sectorBox = QtWidgets.QComboBox(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sectorBox.sizePolicy().hasHeightForWidth())
        self.sectorBox.setSizePolicy(sizePolicy)
        self.sectorBox.setObjectName("sectorBox")
        self.filterMenu.addWidget(self.sectorBox, 0, 1, 1, 1)
        self.currencyLbl = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.currencyLbl.setFont(font)
        self.currencyLbl.setObjectName("currencyLbl")
        self.filterMenu.addWidget(self.currencyLbl, 1, 0, 2, 1)
        self.currencyBox = QtWidgets.QComboBox(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currencyBox.sizePolicy().hasHeightForWidth())
        self.currencyBox.setSizePolicy(sizePolicy)
        self.currencyBox.setObjectName("currencyBox")
        self.filterMenu.addWidget(self.currencyBox, 1, 1, 1, 1)
        self.exchangeBox = QtWidgets.QComboBox(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exchangeBox.sizePolicy().hasHeightForWidth())
        self.exchangeBox.setSizePolicy(sizePolicy)
        self.exchangeBox.setObjectName("exchangeBox")
        self.filterMenu.addWidget(self.exchangeBox, 2, 1, 2, 1)
        self.exchangeLbl = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.exchangeLbl.setFont(font)
        self.exchangeLbl.setObjectName("exchangeLbl")
        self.filterMenu.addWidget(self.exchangeLbl, 3, 0, 1, 1)
        self.controlMenu_2.addLayout(self.filterMenu)
        self.toolsLayout.addLayout(self.controlMenu_2)
        self.tabWidget.addTab(self.toolsInfoTab, "")
        self.positionsTab = QtWidgets.QWidget()
        self.positionsTab.setObjectName("positionsTab")
        self.layoutWidget_6 = QtWidgets.QWidget(self.positionsTab)
        self.layoutWidget_6.setGeometry(QtCore.QRect(50, 20, 761, 504))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.positionsLayout = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.positionsLayout.setContentsMargins(0, 0, 0, 0)
        self.positionsLayout.setObjectName("positionsLayout")
        self.positionsLbl = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.positionsLbl.setFont(font)
        self.positionsLbl.setObjectName("positionsLbl")
        self.positionsLayout.addWidget(self.positionsLbl)
        self.positionsTable = QtWidgets.QTableWidget(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.positionsTable.setFont(font)
        self.positionsTable.setObjectName("positionsTable")
        self.positionsTable.setColumnCount(7)
        self.positionsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.positionsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.positionsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.positionsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.positionsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.positionsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.positionsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.positionsTable.setHorizontalHeaderItem(6, item)
        self.positionsLayout.addWidget(self.positionsTable)
        self.psControlMenu = QtWidgets.QHBoxLayout()
        self.psControlMenu.setObjectName("psControlMenu")
        self.getPosBtn = QtWidgets.QPushButton(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.getPosBtn.setFont(font)
        self.getPosBtn.setObjectName("getPosBtn")
        self.psControlMenu.addWidget(self.getPosBtn)
        self.idAccountLbl_2 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.idAccountLbl_2.setFont(font)
        self.idAccountLbl_2.setObjectName("idAccountLbl_2")
        self.psControlMenu.addWidget(self.idAccountLbl_2)
        self.idAccount2 = QtWidgets.QPlainTextEdit(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idAccount2.sizePolicy().hasHeightForWidth())
        self.idAccount2.setSizePolicy(sizePolicy)
        self.idAccount2.setMaximumSize(QtCore.QSize(16777215, 16777100))
        self.idAccount2.setObjectName("idAccount2")
        self.psControlMenu.addWidget(self.idAccount2)
        self.positionsLayout.addLayout(self.psControlMenu)
        self.tabWidget.addTab(self.positionsTab, "")
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(20, 30, 241, 365))
        self.widget1.setObjectName("widget1")
        self.setupLayuot = QtWidgets.QVBoxLayout(self.widget1)
        self.setupLayuot.setContentsMargins(0, 0, 0, 0)
        self.setupLayuot.setObjectName("setupLayuot")
        self.setupBtn = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.setupBtn.setFont(font)
        self.setupBtn.setObjectName("setupBtn")
        self.setupLayuot.addWidget(self.setupBtn)
        self.exitBtn = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.exitBtn.setFont(font)
        self.exitBtn.setObjectName("exitBtn")
        self.setupLayuot.addWidget(self.exitBtn)
        self.payInBtn = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.payInBtn.setFont(font)
        self.payInBtn.setObjectName("payInBtn")
        self.setupLayuot.addWidget(self.payInBtn)
        self.idAccountLbl_PayIn = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idAccountLbl_PayIn.setFont(font)
        self.idAccountLbl_PayIn.setObjectName("idAccountLbl_PayIn")
        self.setupLayuot.addWidget(self.idAccountLbl_PayIn)
        self.idAccountEdit = QtWidgets.QPlainTextEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idAccountEdit.sizePolicy().hasHeightForWidth())
        self.idAccountEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idAccountEdit.setFont(font)
        self.idAccountEdit.setObjectName("idAccountEdit")
        self.setupLayuot.addWidget(self.idAccountEdit)
        self.sumPayIn = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sumPayIn.setFont(font)
        self.sumPayIn.setObjectName("sumPayIn")
        self.setupLayuot.addWidget(self.sumPayIn)
        self.sumPayInEdit = QtWidgets.QPlainTextEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sumPayInEdit.setFont(font)
        self.sumPayInEdit.setObjectName("sumPayInEdit")
        self.setupLayuot.addWidget(self.sumPayInEdit)
        self.autofillBox = QtWidgets.QCheckBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.autofillBox.setFont(font)
        self.autofillBox.setObjectName("autofillBox")
        self.setupLayuot.addWidget(self.autofillBox)
        self.setupBtn.raise_()
        self.exitBtn.raise_()
        self.accountsTable.raise_()
        self.accountsLabel.raise_()
        self.getAccountsBtn.raise_()
        self.openAccountBtn.raise_()
        self.closeAccountBtn.raise_()
        self.tabWidget.raise_()
        self.sectorBox.raise_()
        self.sectorLbl.raise_()
        self.sectorLbl.raise_()
        self.currencyLbl.raise_()
        self.exchangeLbl.raise_()
        self.sectorBox.raise_()
        self.currencyBox.raise_()
        self.exchangeBox.raise_()
        self.fullSumLbl.raise_()
        self.freeMoneyLbl.raise_()
        self.bondsSumLbl.raise_()
        self.sharesSumLbl.raise_()
        self.etfSumLbl.raise_()
        self.profitLbl.raise_()
        self.fullSumDisp.raise_()
        self.freeMoneyDisp.raise_()
        self.sharesSumDisp.raise_()
        self.bondsSumDisp.raise_()
        self.etfSumDisp.raise_()
        self.profitDisp.raise_()
        self.idAccountLbl_PayIn.raise_()
        self.idAccountEdit.raise_()
        self.sumPayInEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1130, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.accountsLabel.setText(_translate("MainWindow", "Счета"))
        item = self.accountsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.accountsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Статус"))
        self.getAccountsBtn.setText(_translate("MainWindow", "Получить счета"))
        self.openAccountBtn.setText(_translate("MainWindow", "Открыть счет"))
        self.closeAccountBtn.setText(_translate("MainWindow", "Закрыть счет"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.accountsTab), _translate("MainWindow", "Счета"))
        self.portfolioLabel.setText(_translate("MainWindow", "Портфель"))
        self.fullSumLbl.setText(_translate("MainWindow", "Общая стоимость портфеля, руб"))
        self.freeMoneyLbl.setText(_translate("MainWindow", "Свободные деньги, руб"))
        self.sharesSumLbl.setText(_translate("MainWindow", "Сумма акций, руб"))
        self.bondsSumLbl.setText(_translate("MainWindow", "Сумма облигаций, руб"))
        self.etfSumLbl.setText(_translate("MainWindow", "Сумма ETF, руб"))
        self.profitLbl.setText(_translate("MainWindow", "Прибыль/убыток, %"))
        self.getPortfolioBtn.setText(_translate("MainWindow", "Получить портфель"))
        self.idAccountLbl.setText(_translate("MainWindow", "ID счета:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.portfolioTab), _translate("MainWindow", "Баланс"))
        self.toolsLbl.setText(_translate("MainWindow", "Инструменты"))
        item = self.toolsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "TICKER"))
        item = self.toolsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "UID"))
        item = self.toolsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Название"))
        item = self.toolsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Биржа"))
        item = self.toolsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Валюта"))
        item = self.toolsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Сектор"))
        item = self.toolsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Тип инструмента"))
        self.getToolsBtn.setText(_translate("MainWindow", "Получить инструменты"))
        self.sectorLbl.setText(_translate("MainWindow", "Сектор"))
        self.currencyLbl.setText(_translate("MainWindow", "Валюта"))
        self.exchangeLbl.setText(_translate("MainWindow", "Биржа"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.toolsInfoTab), _translate("MainWindow", "Инструменты"))
        self.positionsLbl.setText(_translate("MainWindow", "Портфель"))
        item = self.positionsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "TICKER"))
        item = self.positionsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "UID"))
        item = self.positionsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Название"))
        item = self.positionsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Цена"))
        item = self.positionsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Кол-во лотов"))
        item = self.positionsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Кол-во штук"))
        item = self.positionsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Общая стоимость"))
        self.getPosBtn.setText(_translate("MainWindow", "Получить позиции"))
        self.idAccountLbl_2.setText(_translate("MainWindow", "ID счета:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.positionsTab), _translate("MainWindow", "Позиции"))
        self.setupBtn.setText(_translate("MainWindow", "Запустить"))
        self.exitBtn.setText(_translate("MainWindow", "Остановить"))
        self.payInBtn.setText(_translate("MainWindow", "Пополнить"))
        self.idAccountLbl_PayIn.setText(_translate("MainWindow", "ID счета"))
        self.sumPayIn.setText(_translate("MainWindow", "Сумма пополнения"))
        self.autofillBox.setText(_translate("MainWindow", "Автозаполнение"))